version: '2'
services:
  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    restart: always
    network_mode: host
    # Uncomment the following to set java options
    # environment:
    #   JAVA_OPTS: -Xmx512M
    volumes:
      # Unifi v5.0.7 creates all of these directories (some remain empty)
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - log2:/var/log/unifi
      - run:/usr/lib/unifi/run
      - run2:/run/unifi
      - work:/usr/lib/unifi/work
volumes:
  config:
    driver: local
  log:
    driver: local
  log2:
    driver: local
  run:
    driver: local
  run2:
    driver: local
  work:
    driver: local
